services:
  rabbitmq1:
    image: rabbitmq:3-management
    hostname: rabbitmq1
    environment:
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - ./config:/config
      - ./defs/def.json:/etc/rabbitmq/definitions.json:ro
      - ./defs/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro

    ports:
      - 15672:15672
      - 5672:5672

  rabbitmq2:
    image: rabbitmq:3-management
    hostname: rabbitmq2
    environment:
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - ./config:/config
      - ./defs/def.json:/etc/rabbitmq/definitions.json:ro
      - ./defs/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro

  rabbitmq3:
    image: rabbitmq:3-management
    hostname: rabbitmq3
    environment:
      - RABBITMQ_CONFIG_FILE=/config/rabbitmq
      - RABBITMQ_ERLANG_COOKIE=${RABBITMQ_ERLANG_COOKIE}
    volumes:
      - ./config:/config
      - ./defs/def.json:/etc/rabbitmq/definitions.json:ro
      - ./defs/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro
